org: serverless-cnode
app: serverless-cnode
stage: dev
component: nextjs@dev
name: serverless-cnode

inputs:
  src:
    dist: ./
    hook: npm run build
    exclude:
      - .env
      - '.next/cache/**'
  region: ap-guangzhou
  runtime: Nodejs10.15
  functionName: serverless-cnode
  functionConf:
    timeout: 10
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    enableCORS: true
    customDomains:
      - domain: cnode.yuga.chat
        certificateId: eGesL28k
        pathMappingSet:
          - path: /
            environment: release
        protocols:
          - http
          - https
  staticCdn:
    cosConf:
      bucket: serverless-cnode
    cdnConf:
      # after you deploy CDN once, just set onlyRefresh to true for refresh CDN cache
      onlyRefresh: true
      domain: static.cnode.yuga.chat
      https:
        certId: eGkM75xv
